import { LoggingSchema } from 'lib/prisma/zod'
import { Serialized } from './serialize'
import { z } from 'zod'

export enum APILogEvent {
  WORKER_CREATE = 'WORKER_CREATE',
  WORKER_MODIFY = 'WORKER_MODIFY',
  WORKER_DELETE = 'WORKER_DELETE',
  PLAN_CREATE = 'PLAN_CREATE',
  PLAN_MODIFY = 'PLAN_MODIFY',
  PLAN_DELETE = 'PLAN_DELETE',
  PLAN_PLANNER_START = 'PLAN_PLANNER_START',
  PLAN_JOB_ADD = 'PLAN_JOB_ADD',
  PLAN_JOBS_ADD = 'PLAN_JOBS_ADD',
  PLAN_JOB_DELETE = 'PLAN_JOB_REMOVE',
  PLAN_JOB_MODIFY = 'PLAN_JOB_MODIFY',
  PLAN_RIDE_ADD = 'PLAN_RIDE_ADD',
  PLAN_RIDE_DELETE = 'PLAN_RIDE_DELETE',
  PLAN_RIDE_MODIFY = 'PLAN_RIDE_MODIFY',
  PLAN_UPDATE = 'PLAN_PUBLISH',
  JOB_CREATE = 'JOB_CREATE',
  JOB_MODIFY = 'JOB_MODIFY',
  JOB_DELETE = 'JOB_DELETE',
  CAR_CREATE = 'CAR_CREATE',
  CAR_MODIFY = 'CAR_MODIFY',
  CAR_DELETE = 'CAR_DELETE',
  SMJEVENT_CREATE = 'SMJEVENT_CREATE',
  SMJEVENT_MODIFY = 'SMJEVENT_MODIFY',
  SMJEVENT_DELETE = 'SMJEVENT_DELETE',
  SMJEVENT_APPLICATION_TOGGLE = 'SMJEVENT_APPLICATION_TOGGLE',
  SMJEVENT_PASSWORD_PROTECTION_TOGGLE = 'SMJEVENT_PASSWORD_PROTECTION_TOGGLE',
  SMJEVENT_RECEPTION_PASSWORD_MODIFY = 'SMJEVENT_RECEPTION_PASSWORD_MODIFY',
  SMJEVENT_RECEPTION_PASSWORD_DELETE = 'SMJEVENT_RECEPTION_PASSWORD_DELETE',
  FOOD_DELIVERY_CREATE = 'FOOD_DELIVERY_CREATE',
  FOOD_DELIVERY_DELETE = 'FOOD_DELIVERY_DELETE',
  FOOD_DELIVERY_COMPLETE = 'FOOD_DELIVERY_COMPLETE',
  AREA_CREATE = 'AREA_CREATE',
  AREA_MODIFY = 'AREA_MODIFY',
  AREA_DELETE = 'AREA_DELETE',
  USER_MODIFY = 'USER_MODIFY',
  TOOL_CREATE = 'TOOL_CREATE',
  TOOL_UPDATE = 'TOOL_UPDATE',
  TOOL_DELETE = 'TOOL_DELETE',
  PHOTO_CREATE = 'PHOTO_CREATE',
  PHOTO_UPDATE = 'PHOTO_UPDATE',
  PHOTO_DELETE = 'PHOTO_DELETE',
  POST_CREATE = 'POST_CREATE',
  POST_MODIFY = 'POST_MODIFY',
  POST_DELETE = 'POST_DELETE',
  APPLICATION_CREATE = 'APPLICATION_CREATE',
  APPLICATION_MODIFY = 'APPLICATION_MODIFY',
  APPLICATION_DELETE = 'APPLICATION_DELETE',
  APPLICATION_ACCEPTED = 'APPLICATION_ACCEPTED',
  APPLICATION_REJECTED = 'APPLICATION_REJECTED',
  FOOD_ALLERGY_CREATE = 'FOOD_ALLERGY_CREATE',
  FOOD_ALLERGY_MODIFY = 'FOOD_ALLERGY_MODIFY',
  FOOD_ALLERGY_DELETE = 'FOOD_ALLERGY_DELETE',
  WORK_ALLERGY_CREATE = 'WORK_ALLERGY_CREATE',
  WORK_ALLERGY_MODIFY = 'WORK_ALLERGY_MODIFY',
  WORK_ALLERGY_DELETE = 'WORK_ALLERGY_DELETE',
  SKILL_CREATE = 'SKILL_CREATE',
  SKILL_MODIFY = 'SKILL_MODIFY',
  SKILL_DELETE = 'SKILL_DELETE',
  JOB_TYPE_CREATE = 'JOB_TYPE_CREATE',
  JOB_TYPE_MODIFY = 'JOB_TYPE_MODIFY',
  JOB_TYPE_DELETE = 'JOB_TYPE_DELETE',
  TOOL_NAME_CREATE = 'TOOL_NAME_CREATE',
  TOOL_NAME_MODIFY = 'TOOL_NAME_MODIFY',
  TOOL_NAME_DELETE = 'TOOL_NAME_DELETE',
  TSHIRT_SIZE_CREATE = 'TSHIRT_SIZE_CREATE',
  TSHIRT_SIZE_MODIFY = 'TSHIRT_SIZE_MODIFY',
  TSHIRT_SIZE_DELETE = 'TSHIRT_SIZE_DELETE',
  TSHIRT_COLOR_CREATE = 'TSHIRT_COLOR_CREATE',
  TSHIRT_COLOR_MODIFY = 'TSHIRT_COLOR_MODIFY',
  TSHIRT_COLOR_DELETE = 'TSHIRT_COLOR_DELETE',
}

export type Logging = z.infer<typeof LoggingSchema>

export type FilteredLogs = {
  logs: Logging[]
  total: number
}

export function serializeLogs(logs: FilteredLogs): Serialized {
  return {
    data: JSON.stringify(logs),
  }
}

export function deserializeLogs(serialized: Serialized): FilteredLogs {
  const data = JSON.parse(serialized.data) as FilteredLogs
  return deserializeLogsTime(data)
}

export function deserializeLogsTime(logs: FilteredLogs) {
  const withTime = logs.logs.map(log => ({
    ...log,
    timestamp: new Date(log.timestamp),
  }))
  return { logs: withTime, total: logs.total }
}
